""" Selected geo codes understood by EDGAR API. """

from enum import Enum


class EU(Enum):
    AUT = "AUT"
    BEL = "BEL"
    BGR = "BGR"
    HRV = "HRV"
    CYP = "CYP"
    CZE = "CZE"
    DNK = "DNK"
    EST = "EST"
    FIN = "FIN"
    FRA = "FRA"
    DEU = "DEU"
    GRC = "GRC"
    HUN = "HUN"
    IRL = "IRL"
    ITA = "ITA"
    LVA = "LVA"
    LTU = "LTU"
    LUX = "LUX"
    MLT = "MLT"
    NLD = "NLD"
    POL = "POL"
    PRT = "PRT"
    ROU = "ROU"
    SVK = "SVK"
    SVN = "SVN"
    ESP = "ESP"
    SWE = "SWE"
